### ISSUE TITLE
Greedy matching prevents more specific responder

### ISSUE THREAD

**Issue by NickLarsenNZ** [NickLarsenNZ/mockhttp#23]
No matter the order these responders are supplied, the shortest one matches when the longer path is requested.

```yaml
responders:
- when:
  http:
    method: GET
    path: /v1/providers
...
- when:
  http:
    method: GET
    path: /v1/providers?offset=4
...
```
